- site/gatsby-node.js
- site/src/templates/datadir.tsx
> CSV ファイルの URL を固定にする

- .github/workflows/gh-page-dev.yml
> development サーバを立てる

- site/src/components/PrefectureReport.tsx
> tableau のデータをSpreadsheet から取り込む

- site/gatsby-node.js
- site/src/components/PrefectureReport.tsx
> 都道府県のグラフを変更する

- DEV_SCRIPT.md
- DEV_SITE.md
- README.md
- convert_data.py
- download.py
> 開発用ドキュメントを作る

- .github/workflows/gh-page.yml
> データ取得Actionを定期実行する

- site/gatsby-config.js
- site/package.json
- site/yarn.lock
> Google Analytics 設定

- site/src/layouts/index.tsx
> build error

- README.md
README の気づきの点を少し手をいれてみました。いかがでしょうか。
> etid README

- converter.py
- download.py
> camelot のオプションで、パースの不具合を修正する

- converter.py
> フィールド名を出典元に基づいた正確な表現に変更

- converter.py
- stringutil.py
> demographics.csvの人口(計), 交付件数(男)で一部値が不正

- converter.py
- stringutil.py
> 20190401 の all_prefectures.csv で「交付件数基準日」が一部NULL

- README.md
> GitHubリポジトリのどこかに公開サイトのURLを載せる

- stringutil.py
> summary_by_types.csv の一部ファイルで%付き/なしの表記揺れ

- site/src/components/PrefectureReport.tsx
> 新しい Tableau のリストに合わせて高さを変える

- site/src/components/PrefectureReport.tsx
> Tableauをスマホで見たときに文字が出ない

- converter.py
> 団体区分別の「全国」とその他が別れているのを一つにまとめる

- converter.py
> CSVファイルをBOM付きにする

- converter.py
- download.py
- site/src/content/chant.md
> camelot.read_pdf にオプションを追加すると読み込みエラーがなくなる

- site/.eslintrc
- site/.vscode/settings.json
- site/package.json
- site/src/components/Header.tsx
- site/src/components/PrefectureReport.tsx
- site/src/pages/index.tsx
- site/yarn.lock
環境構築時にESLintのエラーを複数発見したので修正しました
> chore(lint): fix ESLint errors

- site/.eslintrc
- site/.vscode/settings.json
- site/package.json
- site/src/components/Header.tsx
- site/src/components/PrefectureReport.tsx
- site/src/hooks/index.ts
- site/src/hooks/useMeta.ts
- site/src/layouts/index.tsx
- site/src/pages/index.tsx
- site/yarn.lock
close #124 
汎用的なものではないですが、一旦ヘッダーにあるページに対応しました
#128 のまま作業してしまったので、#128 がマージされ次第みていただいたほうがいいかもです
> feat: dynamic site title

- site/src/components/Head.tsx
- site/src/components/Meta.tsx
- site/src/layouts/index.tsx
- site/src/pages/404.tsx
- site/src/pages/data.tsx
- site/src/templates/page.tsx
close #124 
[![Image from Gyazo](https://i.gyazo.com/918d81baa46a80a26bab5084b6ac6232.png)](https://gyazo.com/918d81baa46a80a26bab5084b6ac6232)
後ほど消しますがこちらで確認しました https://yokinist.github.io/mynumbercard_statistics/chant/
> fix: apply page title as og:title

- convert_data.py
close #119 
`/static/data/{ymd}/*.csv` -> `/static/data/latest/*.csv`
※ 7月時点でのダウンロードデータで convert
[![Image from Gyazo](https://i.gyazo.com/e3835451db3aeb4698a2f56e3b4b60c0.png)](https://gyazo.com/e3835451db3aeb4698a2f56e3b4b60c0)
[![Image from Gyazo](https://i.gyazo.com/738eaef6ca846545a64c92ee63288daa.png)](https://gyazo.com/738eaef6ca846545a64c92ee63288daa)
[![Image from Gyazo](https://i.gyazo.com/5bf9c689f025b88b486318818c79f1f0.png)](https://gyazo.com/5bf9c689f025b88b486318818c79f1f0)
[![Image from Gyazo](https://i.gyazo.com/780effc4829d78ce8297678c2616d920.png)](https://gyazo.com/780effc4829d78ce8297678c2616d920)
> fix: latest data dir

- Dockerfile
#173 で指摘されていた、生データのダウンロードに失敗する問題を解決するパッチです。
> 不足しているライブラリの追加

- mynumbercard_data/download.py
> close #190 fix url parse method

- .github/workflows/gh-page-dev.yml
> update node version
